version: "3.8"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-tracker}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB:-tracker}"
      APP_ENV: "development"
      ATTACHMENTS_DIR: "/data/attachments"
    volumes:
      - ./app:/usr/src/app
      - ./attachments:/data/attachments
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  streamlit:
    image: python:3.11-slim
    depends_on:
      - db
      - app
    volumes:
      - ./ui:/usr/src/ui
      - ./attachments:/data/attachments
    working_dir: /usr/src/ui
    env_file:
      - .env
    command: ["streamlit", "run", "streamlit_app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
    ports:
      - "8501:8501"

  rclone:
    image: rclone/rclone:latest
    volumes:
      - ./infra/rclone:/config/rclone:ro
      - ./backups:/backups
    entrypoint: ["sleep", "infinity"]
    # Use this container to run manual or scheduled rclone sync jobs via `docker compose exec rclone ...`

volumes:
  db_data:
